version: '3'

services:
    mysql:
        #image: mysql:8.0.17
        build: .
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: logindemo
            MYSQL_USER: javayhu
            MYSQL_PASSWORD: javayhu
        ports:
            - "3308:3306"
        restart: always

    adminer:
        image: adminer
        ports:
            - "8080:8080"

