// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.tencent.logindemo.proto;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string password = 2;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 2;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string device = 3;</code>
   * @return The device.
   */
  java.lang.String getDevice();
  /**
   * <code>string device = 3;</code>
   * @return The bytes for device.
   */
  com.google.protobuf.ByteString
      getDeviceBytes();
}
