// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.tencent.logindemo.proto;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.CommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
   * @return Whether the tokenInfo field is set.
   */
  boolean hasTokenInfo();
  /**
   * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
   * @return The tokenInfo.
   */
  com.tencent.logindemo.proto.TokenInfo getTokenInfo();
  /**
   * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
   */
  com.tencent.logindemo.proto.TokenInfoOrBuilder getTokenInfoOrBuilder();
}
