// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.tencent.logindemo.proto;

/**
 * Protobuf type {@code helloworld.CommonResponse}
 */
public final class CommonResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:helloworld.CommonResponse)
    CommonResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CommonResponse.newBuilder() to construct.
  private CommonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CommonResponse() {
    message_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CommonResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CommonResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            code_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            com.tencent.logindemo.proto.TokenInfo.Builder subBuilder = null;
            if (tokenInfo_ != null) {
              subBuilder = tokenInfo_.toBuilder();
            }
            tokenInfo_ = input.readMessage(com.tencent.logindemo.proto.TokenInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tokenInfo_);
              tokenInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tencent.logindemo.proto.HelloWorldProto.internal_static_helloworld_CommonResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tencent.logindemo.proto.HelloWorldProto.internal_static_helloworld_CommonResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tencent.logindemo.proto.CommonResponse.class, com.tencent.logindemo.proto.CommonResponse.Builder.class);
  }

  public static final int CODE_FIELD_NUMBER = 1;
  private int code_;
  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  @java.lang.Override
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKENINFO_FIELD_NUMBER = 3;
  private com.tencent.logindemo.proto.TokenInfo tokenInfo_;
  /**
   * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
   * @return Whether the tokenInfo field is set.
   */
  @java.lang.Override
  public boolean hasTokenInfo() {
    return tokenInfo_ != null;
  }
  /**
   * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
   * @return The tokenInfo.
   */
  @java.lang.Override
  public com.tencent.logindemo.proto.TokenInfo getTokenInfo() {
    return tokenInfo_ == null ? com.tencent.logindemo.proto.TokenInfo.getDefaultInstance() : tokenInfo_;
  }
  /**
   * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
   */
  @java.lang.Override
  public com.tencent.logindemo.proto.TokenInfoOrBuilder getTokenInfoOrBuilder() {
    return getTokenInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (code_ != 0) {
      output.writeInt32(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (tokenInfo_ != null) {
      output.writeMessage(3, getTokenInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, code_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (tokenInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTokenInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tencent.logindemo.proto.CommonResponse)) {
      return super.equals(obj);
    }
    com.tencent.logindemo.proto.CommonResponse other = (com.tencent.logindemo.proto.CommonResponse) obj;

    if (getCode()
        != other.getCode()) return false;
    if (!getMessage()
        .equals(other.getMessage())) return false;
    if (hasTokenInfo() != other.hasTokenInfo()) return false;
    if (hasTokenInfo()) {
      if (!getTokenInfo()
          .equals(other.getTokenInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    if (hasTokenInfo()) {
      hash = (37 * hash) + TOKENINFO_FIELD_NUMBER;
      hash = (53 * hash) + getTokenInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tencent.logindemo.proto.CommonResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tencent.logindemo.proto.CommonResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tencent.logindemo.proto.CommonResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code helloworld.CommonResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:helloworld.CommonResponse)
      com.tencent.logindemo.proto.CommonResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tencent.logindemo.proto.HelloWorldProto.internal_static_helloworld_CommonResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tencent.logindemo.proto.HelloWorldProto.internal_static_helloworld_CommonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tencent.logindemo.proto.CommonResponse.class, com.tencent.logindemo.proto.CommonResponse.Builder.class);
    }

    // Construct using com.tencent.logindemo.proto.CommonResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      code_ = 0;

      message_ = "";

      if (tokenInfoBuilder_ == null) {
        tokenInfo_ = null;
      } else {
        tokenInfo_ = null;
        tokenInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tencent.logindemo.proto.HelloWorldProto.internal_static_helloworld_CommonResponse_descriptor;
    }

    @java.lang.Override
    public com.tencent.logindemo.proto.CommonResponse getDefaultInstanceForType() {
      return com.tencent.logindemo.proto.CommonResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.tencent.logindemo.proto.CommonResponse build() {
      com.tencent.logindemo.proto.CommonResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tencent.logindemo.proto.CommonResponse buildPartial() {
      com.tencent.logindemo.proto.CommonResponse result = new com.tencent.logindemo.proto.CommonResponse(this);
      result.code_ = code_;
      result.message_ = message_;
      if (tokenInfoBuilder_ == null) {
        result.tokenInfo_ = tokenInfo_;
      } else {
        result.tokenInfo_ = tokenInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tencent.logindemo.proto.CommonResponse) {
        return mergeFrom((com.tencent.logindemo.proto.CommonResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tencent.logindemo.proto.CommonResponse other) {
      if (other == com.tencent.logindemo.proto.CommonResponse.getDefaultInstance()) return this;
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.hasTokenInfo()) {
        mergeTokenInfo(other.getTokenInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tencent.logindemo.proto.CommonResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tencent.logindemo.proto.CommonResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int code_ ;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 1;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     * @return This builder for chaining.
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     * @return This builder for chaining.
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private com.tencent.logindemo.proto.TokenInfo tokenInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tencent.logindemo.proto.TokenInfo, com.tencent.logindemo.proto.TokenInfo.Builder, com.tencent.logindemo.proto.TokenInfoOrBuilder> tokenInfoBuilder_;
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     * @return Whether the tokenInfo field is set.
     */
    public boolean hasTokenInfo() {
      return tokenInfoBuilder_ != null || tokenInfo_ != null;
    }
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     * @return The tokenInfo.
     */
    public com.tencent.logindemo.proto.TokenInfo getTokenInfo() {
      if (tokenInfoBuilder_ == null) {
        return tokenInfo_ == null ? com.tencent.logindemo.proto.TokenInfo.getDefaultInstance() : tokenInfo_;
      } else {
        return tokenInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     */
    public Builder setTokenInfo(com.tencent.logindemo.proto.TokenInfo value) {
      if (tokenInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tokenInfo_ = value;
        onChanged();
      } else {
        tokenInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     */
    public Builder setTokenInfo(
        com.tencent.logindemo.proto.TokenInfo.Builder builderForValue) {
      if (tokenInfoBuilder_ == null) {
        tokenInfo_ = builderForValue.build();
        onChanged();
      } else {
        tokenInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     */
    public Builder mergeTokenInfo(com.tencent.logindemo.proto.TokenInfo value) {
      if (tokenInfoBuilder_ == null) {
        if (tokenInfo_ != null) {
          tokenInfo_ =
            com.tencent.logindemo.proto.TokenInfo.newBuilder(tokenInfo_).mergeFrom(value).buildPartial();
        } else {
          tokenInfo_ = value;
        }
        onChanged();
      } else {
        tokenInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     */
    public Builder clearTokenInfo() {
      if (tokenInfoBuilder_ == null) {
        tokenInfo_ = null;
        onChanged();
      } else {
        tokenInfo_ = null;
        tokenInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     */
    public com.tencent.logindemo.proto.TokenInfo.Builder getTokenInfoBuilder() {
      
      onChanged();
      return getTokenInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     */
    public com.tencent.logindemo.proto.TokenInfoOrBuilder getTokenInfoOrBuilder() {
      if (tokenInfoBuilder_ != null) {
        return tokenInfoBuilder_.getMessageOrBuilder();
      } else {
        return tokenInfo_ == null ?
            com.tencent.logindemo.proto.TokenInfo.getDefaultInstance() : tokenInfo_;
      }
    }
    /**
     * <code>.helloworld.TokenInfo tokenInfo = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tencent.logindemo.proto.TokenInfo, com.tencent.logindemo.proto.TokenInfo.Builder, com.tencent.logindemo.proto.TokenInfoOrBuilder> 
        getTokenInfoFieldBuilder() {
      if (tokenInfoBuilder_ == null) {
        tokenInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tencent.logindemo.proto.TokenInfo, com.tencent.logindemo.proto.TokenInfo.Builder, com.tencent.logindemo.proto.TokenInfoOrBuilder>(
                getTokenInfo(),
                getParentForChildren(),
                isClean());
        tokenInfo_ = null;
      }
      return tokenInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:helloworld.CommonResponse)
  }

  // @@protoc_insertion_point(class_scope:helloworld.CommonResponse)
  private static final com.tencent.logindemo.proto.CommonResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tencent.logindemo.proto.CommonResponse();
  }

  public static com.tencent.logindemo.proto.CommonResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CommonResponse>
      PARSER = new com.google.protobuf.AbstractParser<CommonResponse>() {
    @java.lang.Override
    public CommonResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CommonResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CommonResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CommonResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tencent.logindemo.proto.CommonResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

