// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package com.tencent.logindemo.proto;

public interface RefreshTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.RefreshTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device = 1;</code>
   * @return The device.
   */
  java.lang.String getDevice();
  /**
   * <code>string device = 1;</code>
   * @return The bytes for device.
   */
  com.google.protobuf.ByteString
      getDeviceBytes();

  /**
   * <code>string token = 2;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();
}
