// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logindemo.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>

namespace logindemo {

struct CommonReponse final {
    int32_t code;
    std::string msg;
    std::string data;

    CommonReponse(int32_t code_,
                  std::string msg_,
                  std::string data_)
    : code(std::move(code_))
    , msg(std::move(msg_))
    , data(std::move(data_))
    {}
};

}  // namespace logindemo
