// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logindemo.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

namespace logindemo {

class HelloWorld {
public:
    virtual ~HelloWorld() {}

    static std::shared_ptr<HelloWorld> create(const std::string & host, int32_t port);

    virtual std::string get_hello_world() = 0;

    virtual std::string sayHello(const std::string & msg) = 0;
};

}  // namespace logindemo
