// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logindemo.djinni

#include "NativeCommonReponse.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeCommonReponse::NativeCommonReponse() = default;

NativeCommonReponse::~NativeCommonReponse() = default;

auto NativeCommonReponse::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeCommonReponse>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::I32::fromCpp(jniEnv, c.code)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.msg)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.data)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeCommonReponse::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeCommonReponse>::get();
    return {::djinni::I32::toCpp(jniEnv, jniEnv->GetIntField(j, data.field_mCode)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mMsg)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mData))};
}

}  // namespace djinni_generated
