// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logindemo.djinni

#pragma once

#include "common_reponse.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeCommonReponse final {
public:
    using CppType = ::logindemo::CommonReponse;
    using JniType = jobject;

    using Boxed = NativeCommonReponse;

    ~NativeCommonReponse();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeCommonReponse();
    friend ::djinni::JniClass<NativeCommonReponse>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/tencent/logindemo/djinni/CommonReponse") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(ILjava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mCode { ::djinni::jniGetFieldID(clazz.get(), "mCode", "I") };
    const jfieldID field_mMsg { ::djinni::jniGetFieldID(clazz.get(), "mMsg", "Ljava/lang/String;") };
    const jfieldID field_mData { ::djinni::jniGetFieldID(clazz.get(), "mData", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
