version: '3'

services:
    #数据库使用MySQL 8.0.17
    mysql:
        build: ./mysql
        container_name: helloworld-service_mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: logindemo
            MYSQL_USER: javayhu
            MYSQL_PASSWORD: javayhu
        ports:
            - "3306:3306"
        restart: always

    #查看数据库内容工具adminer
    adminer:
        image: adminer
        container_name: helloworld-service_adminer
        ports:
            - "8080:8080"

    #由gRPC java搭建的后台服务
    server:
        build: ./grpc
        container_name: helloworld-service_grpc
        ports:
            - "50051:50051"
        depends_on:
            - mysql
        links:
            - mysql:mysql
        restart: always
