// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logindemo.djinni

#import <Foundation/Foundation.h>
@class LDHelloWorld;


@interface LDHelloWorld : NSObject

+ (nullable LDHelloWorld *)create;

- (nonnull NSString *)getHelloWorld;

@end
