// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from logindemo.djinni

package com.tencent.logindemo.djinni;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class HelloWorld {
    public abstract CommonReponse signup(String name, String password, String device);

    public abstract CommonReponse login(String name, String password, String device);

    public abstract CommonReponse logout(String token);

    public abstract CommonReponse refreshToken(String token);

    public abstract String sayHello(String msg);

    public static HelloWorld create(String host, int port)
    {
        return CppProxy.create(host,
                               port);
    }

    private static final class CppProxy extends HelloWorld
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public CommonReponse signup(String name, String password, String device)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_signup(this.nativeRef, name, password, device);
        }
        private native CommonReponse native_signup(long _nativeRef, String name, String password, String device);

        @Override
        public CommonReponse login(String name, String password, String device)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_login(this.nativeRef, name, password, device);
        }
        private native CommonReponse native_login(long _nativeRef, String name, String password, String device);

        @Override
        public CommonReponse logout(String token)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_logout(this.nativeRef, token);
        }
        private native CommonReponse native_logout(long _nativeRef, String token);

        @Override
        public CommonReponse refreshToken(String token)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_refreshToken(this.nativeRef, token);
        }
        private native CommonReponse native_refreshToken(long _nativeRef, String token);

        @Override
        public String sayHello(String msg)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_sayHello(this.nativeRef, msg);
        }
        private native String native_sayHello(long _nativeRef, String msg);

        public static native HelloWorld create(String host, int port);
    }
}
