version: '3'

services:
    #数据库mysql
    mysql:
        build: ./mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: logindemo
            MYSQL_USER: javayhu
            MYSQL_PASSWORD: javayhu
        ports:
            - "3308:3306"
        restart: always

    #查看数据库内容工具adminer
    adminer:
        image: adminer
        ports:
            - "8080:8080"

    #由gRPC搭建的后台服务
    server:
        build: ./gRPC
        ports:
            - "50051:50051"
        depends_on:
            - mysql
        links:
            - mysql:mysql
        restart: always
